<?php
include("c-seguridad_cliente.php");
include("c-menu.php");
echo"<link rel='website icon' type='png' href='img/logo.png'>";
echo"<link rel='stylesheet' href='css/style.css'>";
echo"<link rel='stylesheet'  href='css/nav.css'>";
echo"<link rel='stylesheet' href='css/profile.css'>";
echo"<link rel='stylesheet' href='css/experiences.css'>";
echo"<link rel='stylesheet' href='css/contact.css'>";
echo"<link rel='stylesheet' href='css/formurario.css'>";
echo"<img class='logo-menu'";
echo"height='130'";
echo"width='130'";
echo"src='img/logo.png' ";
echo"alt='Help Paws'";
echo"/>";
echo"<div>";
echo"    <section class='contact' id='contact'>";
echo"       <h2 class='contact-title'>contactos</h2>";
echo"        <div class='contact-details'>";
echo"            <div class='contact-details-group'>";
echo"                <p class='contact-label'>Dirección:</p>";
echo"                <p class='contact-text'>Bogotá, colombia</p>";
echo"            </div>";
echo"            <div class='contact-details-group'>";
echo"                <p class='contact-label'>Email:</p>";
echo"                <p class='contact-text'>helppaws@gmail.com</p>";
echo"            </div>";
echo"            <div class='contact-details-group'>";
echo"                <p class='contact-text'>Deje su mensaje y con gusto le responderemos</p>";
echo"            </div>";
echo"        </div>";
echo"            <form  class='contact-form'>";
echo"                <div class='contact-form-group'>";
echo "                  Tipo de mensaje"; echo "<br/>";
echo "                  <select name='documento' required>";
echo "                  <option value=''>Seleccione:</option>";
echo"                   <input  value='' required ' name='name' id='name'>";
echo"           </div>";
echo"                <div class='contact-form-group'>";
echo"                   <label for='name'>Nombre:</label>";
echo"                   <input required type='text' name='name' id='name'>";
echo"           </div>";
echo"           <div class='contact-form-group'>";
echo"               <label for='email'>Email:</label>";
echo"               <input required type='email' name='email' id='email'>";
echo"           </div>";
echo"           <div class='contact-form-group'>";
echo"               <label for='message'>Mensaje:</label>";
echo"               <textarea  required name='message' id='message'  rows='6'></textarea>";
echo"           </div>";
echo"           <button type='submit' class='contact-form-submit' >Enviar</button>";
echo"       </form>";
echo"       <nav class='social'>";
echo"           <ul class='social-list'>";
echo"               <li>";
echo"                   <a href='#twitter'>";
echo"                       <img src='img/social/twitter.svg' alt='twitter profile'>";
echo"                   </a>";
echo"               </li>";
echo"               <li class='social-item'>";
echo"                   <a href='#youtube' class='social-link'>";
echo"                       <img src='img/social/youtube.svg' alt='youtube profile'>";
echo"                   </a>";
echo"               </li>";
echo"               <li class='social-item'>";
echo"                   <a href='#github' class='social-item'>";
echo"                       <img src='img/social/github.svg' alt='github profile'>";
echo"                   </a>";
echo"               </li>";
echo"               <li class='social-item'>";
echo"                   <a href='#linkedin'>";
echo"                       <img src='img/social/linkedin.svg' alt='linkedin profile'>";
echo"                   </a>";
echo"               </li>";
echo"           </ul>";
echo"       </nav>"; 
echo"    </section>";
echo"</div>";
?>